#!/bin/sh
### BEGIN INIT INFO
# Provides:          dns-split
# Required-Start:    $syslog $remote_fs $network zookeeper
# Required-Stop:     $syslog $remote_fs $network zookeeper
# Should-Start:      fam
# Should-Stop:       fam
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

DAEMON=/srv/dns-split/dns.py
NAME="dns-split"
PIDFILE=/var/run/$NAME.pid

set -e
. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $NAME"
        if ! start-stop-daemon --start --background --exec $DAEMON --make-pidfile --pidfile $PIDFILE --quiet -- $DAEMON_OPTS; then
            log_end_msg 1
            exit 1
        else
            log_end_msg 0
        fi
        ;;
    stop)
        log_daemon_msg "Stopping $NAME"
        if start-stop-daemon --stop --oknodo --pidfile $PIDFILE --quiet; then
            rm -f $PIDFILE
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    status)
        if [ -f $PIDFILE ]; then
            status_of_proc -p "$PIDFILE" "$DAEMON" $NAME
        else
            echo "$NAME is not running."
            exit 1
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
esac

